log4j.rootLogger = INFO, LOG1

# We configure our logger to log in a file
log4j.appender.LOG1=org.apache.log4j.FileAppender
log = ./logs/App/log4j
log4j.appender.LOG1.File=${log}/log.out

# We configure the format of output logged messages:
# %d: timestamp  %p: priority  %t: thread  %C: the class  %m: the message  %n: return character
log4j.appender.LOG1.layout=org.apache.log4j.PatternLayout
log4j.appender.LOG1.layout.conversionPattern=%d %p [%t] %C - %m%n
